<a href="https://colab.research.google.com/github/PelumiOgunlusi/PelumiOgunlusi/blob/main/Hamoye_Stage_C_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING THE NECESSARY LIBRARIES**

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
! gdown --id 1Hkg2h9vawtLTzjszQGuwbEyWnx7Rrk9x

Downloading...
From: https://drive.google.com/uc?id=1Hkg2h9vawtLTzjszQGuwbEyWnx7Rrk9x
To: /content/Data_for_UCI_named.csv
100% 2.42M/2.42M [00:00<00:00, 47.0MB/s]


**READING THE DATASET**

In [21]:
uci = pd.read_csv('/content/Data_for_UCI_named.csv')

In [22]:
uci.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

**DROPPING THE STAB COLUMN**

In [23]:
uci.drop('stab',axis=1,inplace = True)

In [24]:
uci.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [25]:
uci.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [26]:
uci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stabf   10000 non-null  object 
dtypes: float64(12), object(1)
memory usage: 1015.8+ KB


**LABELLING THE TARGET AND FEATURES**

In [27]:
x = uci.drop(columns='stabf')
y = uci['stabf']

**LABEL ENCODING THE Y VARIABLE TO INCLUDE ONLY INCLUDE ONE'S AND ZERO'S**

In [28]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [35]:
y.dtype

dtype('int64')

**SPLITTING THE DATASET INTO TRAINING(80) AND TESTING DATASET (20)**

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [51]:
y_train

array([1, 1, 1, ..., 1, 1, 0])

**TRANSFORMING THE DATASET USING STANDARD SCALER**

In [43]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled_train = scaler.fit_transform(x_train)
y_scaled_train = scaler.fit_transform(y_train.reshape(-1,1))
x_scaled_test = scaler.fit_transform(x_test)

**FITTING THE DATASET WITH THE RANDOM FOREST CLASSIFIER**

In [55]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 1)
rfc.fit(x_scaled_train, (y_train))
y_pred = rfc.predict(x_scaled_test)
y_pred

array([1, 1, 0, ..., 0, 0, 1])

In [75]:
from sklearn.metrics import accuracy_score

# printing the accuracy of the model
print(accuracy_score(y_test, y_pred))

0.928


**FITTING THE DATASET WITH THE EXTRA TREES CLASSIFIER**

In [57]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(random_state = 1)
etc.fit(x_scaled_train, (y_train))
y_pred_etc = etc.predict(x_scaled_test)
y_pred_etc

array([1, 1, 0, ..., 0, 1, 1])

In [58]:
from sklearn.metrics import accuracy_score

# printing the accuracy of the model
print(accuracy_score(y_test, y_pred_etc))

0.926


**FITTING THE DATASET WITH THE XGBOOST CLASSIFIER**

In [60]:
from xgboost import XGBClassifier
xgbc = XGBClassifier(random_state = 1)
xgbc.fit(x_scaled_train, (y_train))
y_pred_xgbc = xgbc.predict(x_scaled_test)
y_pred_xgbc

array([1, 1, 0, ..., 0, 1, 1])

In [61]:
from sklearn.metrics import accuracy_score

# printing the accuracy of the model
print(accuracy_score(y_test, y_pred_xgbc))

0.919


**FITTING THE DATASET WITH THE LIGHT GRADIENT BOOSTING MODEL CLASSIFIER**

In [62]:
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(random_state = 1)
lgbm.fit(x_scaled_train, (y_train))
y_pred_lgbm = lgbm.predict(x_scaled_test)
y_pred_lgbm

array([1, 1, 0, ..., 0, 1, 1])

In [63]:
from sklearn.metrics import accuracy_score

# printing the accuracy of the model
print(accuracy_score(y_test, y_pred_lgbm))

0.9355
